### ISSUE TITLE
Where should the container be in initialized in ASP.NET Core?

### ISSUE THREAD

**Issue by YehudahA** [simpleinjector/Documentation#37]
In your [ASP.NET Core MVC Integration Guide](https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) the ```InitializeContainer``` made in ```Configure``` method.

Is this the right practice?
According to asp net documentation, ```Configure``` is used to configure the request handling, and ```ConfigureServices``` is used to registering services.

**Comment by dotnetjunkie** [comment]
The Simple Injector container is *not* the .NET Core built-in container and different advice applies here. 

During the `ConfigureServices` phase, registrations are made into the built-in configuration system (the built-in container), and during this time you can as well make the registrations for Simple Injector. During this time however, the built-in configuration system is built and framework services can't be resolved yet from the system. It's only during the `Configure` phase that services can be resolved from the ASP.NET configuration system. 

Resolving types from the built-in configuration system is often needed, because your application needs to interact with framework supplied components. This will typically mean that you create adapters for application-specific abstractions and the adapter will internally callback into framework components. Since those framework components can only be resolved during the `Configure` phase, it's not possible to register those adapters into Simple Injector before the `Configure` phase.

So yes, you can move most of your registrations to `ConfigureServices`. Where to place them is completely up to you, but you will at least have your adapter registrations in the `Configure` phase.

**Comment by dotnetjunkie** [comment]
This question is better suited on https://github.com/simpleinjector/SimpleInjector/issues/ instead.

**Comment by YehudahA** [comment]
@dotnetjunkie, Thank you very much!
